// Difficulty changes decisions/reaction/aim only, never health or weapon stats.
export const BOT_DIFFICULTIES = Object.freeze({
  easy: {
    label: "Easy",
    think: 0.2,
    reaction: 0.75,
    turn: 2.2,
    error: 0.055,
    range: 28,
    fov: 115,
    burst: 0.3,
    pause: 0.55,
    cover: false,
    grenades: false,
  },
  normal: {
    label: "Normal",
    think: 0.14,
    reaction: 0.42,
    turn: 3.2,
    error: 0.028,
    range: 40,
    fov: 125,
    burst: 0.5,
    pause: 0.35,
    cover: true,
    grenades: false,
  },
  hard: {
    label: "Hard",
    think: 0.1,
    reaction: 0.26,
    turn: 4.2,
    error: 0.014,
    range: 48,
    fov: 135,
    burst: 0.65,
    pause: 0.25,
    cover: true,
    grenades: true,
  },
});
export const BOT_NAMES = [
  "Rook",
  "Kestrel",
  "Vega",
  "Flint",
  "Echo",
  "Reef",
  "Atlas",
  "Ember",
  "Mako",
];
